[package]
name = "rust-music-bot-futures"
version = "0.1.0"
authors = ["SpongyBacon <spongybacon@hotmail.co.uk>"]

[dependencies]
env_logger = "0.5"
error-chain = "0.12"
futures-await = "0.1"
futures-stream-select-all = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
lavalink = { git = "https://github.com/serenity-rs/lavalink.rs" }
lavalink-futures = { git = "https://github.com/zeyla/lavalink-futures" }
log = "0.4"
native-tls = "0.2"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4"
tungstenite = "0.6"
tokio-core = "0.1"
websocket = "0.20"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "futures"
default-features = true
