[package]
name = "rust-music-bot-futures"
version = "0.1.0"
authors = ["SpongyBacon <spongybacon@hotmail.co.uk>"]

[dependencies]
log = "~0.4"
env_logger = "~0.5"
lavalink-futures = { git = "https://github.com/zeyla/lavalink-futures" }
futures-await = "~0.1"
tokio-core = "0.1.12"
hyper = "0.11.22"
hyper-tls = "0.1.2"
native-tls = "0.1.5"
error-chain = "0.11.0"
tungstenite = "0.5.3"
serde_json = "1.0.10"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity"
branch = "futures"
default-features = true