bot_prefix = "%"
discord_token = "Bot MTYzMzM0MjM5NTY2MTY4MDY0.DZmZxg.ur1NsRmwsr0P2_IfBg6JuefV2f8"
lavalink_shards = 1
lavalink_user_id = 163334239566168064
postgres_addr = "postgresql://dabbot_dev:CkQbv8TkV3XIn8gO@158.69.250.213:5432/dabbot_dev"
owners = [
    87164639695110144, # spong
    114941315417899012, # zeyla
    66078337084162048 # foxbot
]

[[lavalink_nodes]]
http_host = "http://skippa.dabbot.org:2333"
websocket_host = "http://skippa.dabbot.org:8012"
password = "ye178e81te1en0921ety12ne1"
